-- OneThree page counter for Supabase.
-- Run this file once in Supabase Dashboard -> SQL Editor.

create table if not exists public.page_counters (
  id bigint generated by default as identity primary key,
  path text not null unique,
  title text,
  pv bigint not null default 0,
  uv bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.page_visitors (
  id bigint generated by default as identity primary key,
  path text not null,
  visitor_id text not null,
  created_at timestamptz not null default now(),
  unique (path, visitor_id)
);

alter table public.page_counters enable row level security;
alter table public.page_visitors enable row level security;

drop function if exists public.increment_page_counter(text, text, text);

create function public.increment_page_counter(
  p_path text,
  p_title text,
  p_visitor_id text
)
returns table(page_path text, pv bigint, uv bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_visitors integer := 0;
begin
  insert into public.page_counters as counter(path, title, pv, uv)
  values (p_path, p_title, 0, 0)
  on conflict on constraint page_counters_path_key do update
  set title = excluded.title,
      updated_at = now();

  insert into public.page_visitors(path, visitor_id)
  values (p_path, p_visitor_id)
  on conflict on constraint page_visitors_path_visitor_id_key do nothing;

  get diagnostics inserted_visitors = row_count;

  update public.page_counters as counter
  set pv = counter.pv + 1,
      uv = counter.uv + inserted_visitors,
      updated_at = now()
  where counter.path = p_path;

  return query
  select counter.path, counter.pv, counter.uv
  from public.page_counters as counter
  where counter.path = p_path;
end;
$$;

grant execute on function public.increment_page_counter(text, text, text) to anon, authenticated;
