-- OneThree page counter for Supabase.
-- Run this file once in Supabase Dashboard -> SQL Editor.

create table if not exists public.page_counters (
  id bigint generated by default as identity primary key,
  path text not null unique,
  title text,
  pv bigint not null default 0,
  uv bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.page_visitors (
  id bigint generated by default as identity primary key,
  path text not null,
  visitor_id text not null,
  created_at timestamptz not null default now(),
  unique (path, visitor_id)
);

create table if not exists public.visitor_locations (
  id bigint generated by default as identity primary key,
  visitor_id text not null unique,
  country_code text,
  country_name text,
  region text,
  city text,
  latitude double precision,
  longitude double precision,
  visits bigint not null default 1,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

alter table public.page_counters enable row level security;
alter table public.page_visitors enable row level security;
alter table public.visitor_locations enable row level security;

drop function if exists public.increment_page_counter(text, text, text);

create function public.increment_page_counter(
  p_path text,
  p_title text,
  p_visitor_id text
)
returns table(page_path text, pv bigint, uv bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_visitors integer := 0;
begin
  insert into public.page_counters as counter(path, title, pv, uv)
  values (p_path, p_title, 0, 0)
  on conflict on constraint page_counters_path_key do update
  set title = excluded.title,
      updated_at = now();

  insert into public.page_visitors(path, visitor_id)
  values (p_path, p_visitor_id)
  on conflict on constraint page_visitors_path_visitor_id_key do nothing;

  get diagnostics inserted_visitors = row_count;

  update public.page_counters as counter
  set pv = counter.pv + 1,
      uv = counter.uv + inserted_visitors,
      updated_at = now()
  where counter.path = p_path;

  return query
  select counter.path, counter.pv, counter.uv
  from public.page_counters as counter
  where counter.path = p_path;
end;
$$;

grant execute on function public.increment_page_counter(text, text, text) to anon, authenticated;

drop function if exists public.record_visitor_location(text, text, text, text, text, double precision, double precision);

create function public.record_visitor_location(
  p_visitor_id text,
  p_country_code text,
  p_country_name text,
  p_region text,
  p_city text,
  p_latitude double precision,
  p_longitude double precision
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_visitor_id is null
    or length(trim(p_visitor_id)) = 0
    or p_latitude is null
    or p_longitude is null
    or p_latitude < -90
    or p_latitude > 90
    or p_longitude < -180
    or p_longitude > 180 then
    return;
  end if;

  insert into public.visitor_locations as location(
    visitor_id,
    country_code,
    country_name,
    region,
    city,
    latitude,
    longitude,
    visits,
    last_seen_at
  )
  values (
    trim(p_visitor_id),
    nullif(upper(trim(coalesce(p_country_code, ''))), ''),
    nullif(trim(coalesce(p_country_name, '')), ''),
    nullif(trim(coalesce(p_region, '')), ''),
    nullif(trim(coalesce(p_city, '')), ''),
    p_latitude,
    p_longitude,
    1,
    now()
  )
  on conflict on constraint visitor_locations_visitor_id_key do update
  set country_code = excluded.country_code,
      country_name = excluded.country_name,
      region = excluded.region,
      city = excluded.city,
      latitude = excluded.latitude,
      longitude = excluded.longitude,
      visits = location.visits + 1,
      last_seen_at = now();
end;
$$;

grant execute on function public.record_visitor_location(text, text, text, text, text, double precision, double precision) to anon, authenticated;

drop function if exists public.get_visitor_locations(integer);

create function public.get_visitor_locations(p_limit integer default 250)
returns table(
  country_code text,
  country_name text,
  region text,
  city text,
  latitude double precision,
  longitude double precision,
  visitors bigint,
  visits bigint,
  last_seen_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  with normalized as (
    select
      location.country_code,
      location.country_name,
      case
        when upper(coalesce(location.country_code, '')) = 'SG' then 'Singapore'
        when upper(coalesce(location.country_code, '')) = 'JP'
          and lower(coalesce(location.city, '')) = 'osaka' then 'Osaka'
        when upper(coalesce(location.country_code, '')) = 'CN'
          and lower(coalesce(location.region, '')) = 'beijing'
          and lower(coalesce(location.city, '')) in ('beijing', 'chaowai') then 'Beijing'
        else location.region
      end as region,
      case
        when upper(coalesce(location.country_code, '')) = 'SG' then 'Singapore'
        when upper(coalesce(location.country_code, '')) = 'JP'
          and lower(coalesce(location.city, '')) = 'osaka' then 'Osaka'
        when upper(coalesce(location.country_code, '')) = 'CN'
          and lower(coalesce(location.region, '')) = 'beijing'
          and lower(coalesce(location.city, '')) in ('beijing', 'chaowai') then 'Beijing'
        else location.city
      end as city,
      location.latitude,
      location.longitude,
      location.visits,
      location.last_seen_at
    from public.visitor_locations as location
    where location.latitude is not null
      and location.longitude is not null
  )
  select
    normalized.country_code,
    normalized.country_name,
    normalized.region,
    normalized.city,
    avg(normalized.latitude) as latitude,
    avg(normalized.longitude) as longitude,
    count(*)::bigint as visitors,
    sum(normalized.visits)::bigint as visits,
    max(normalized.last_seen_at) as last_seen_at
  from normalized
  group by
    normalized.country_code,
    normalized.country_name,
    normalized.region,
    normalized.city
  order by visitors desc, visits desc, last_seen_at desc
  limit greatest(1, least(coalesce(p_limit, 250), 500));
$$;

grant execute on function public.get_visitor_locations(integer) to anon, authenticated;
